import type { TwigaRoom, TwigaBooking, TwigaPayment } from './types';

export const MOCK_ROOMS: TwigaRoom[] = [
  { id: 'room-1', name: 'Standard Room 1', type: 'standard', maxGuests: 2, basePrice: 15000000, amenities: ['WiFi', 'AC', 'Flat screen TV'], images: ['https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80'], description: 'Comfortable standard room with modern amenities, air conditioning, and a flat screen TV. Perfect for short or extended stays in Zanzibar.', bedroomCount: 1, bathroomCount: 1 },
  { id: 'room-2', name: 'Standard Room 2', type: 'standard', maxGuests: 2, basePrice: 15000000, amenities: ['WiFi', 'AC', 'Flat screen TV'], images: ['https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=800&q=80'], description: 'Comfortable standard room with modern amenities, air conditioning, and a flat screen TV. Perfect for short or extended stays in Zanzibar.', bedroomCount: 1, bathroomCount: 1 },
  { id: 'room-3', name: 'Standard Room 3', type: 'standard', maxGuests: 2, basePrice: 15000000, amenities: ['WiFi', 'AC', 'Flat screen TV'], images: ['https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800&q=80'], description: 'Comfortable standard room with modern amenities, air conditioning, and a flat screen TV. Perfect for short or extended stays in Zanzibar.', bedroomCount: 1, bathroomCount: 1 },
  { id: 'room-4', name: 'Standard Room 4', type: 'standard', maxGuests: 2, basePrice: 15000000, amenities: ['WiFi', 'AC', 'Flat screen TV'], images: ['https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800&q=80'], description: 'Comfortable standard room with modern amenities, air conditioning, and a flat screen TV. Perfect for short or extended stays in Zanzibar.', bedroomCount: 1, bathroomCount: 1 },
  { id: 'room-5', name: 'Standard Room 5', type: 'standard', maxGuests: 2, basePrice: 15000000, amenities: ['WiFi', 'AC', 'Flat screen TV'], images: ['https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&q=80'], description: 'Comfortable standard room with modern amenities, air conditioning, and a flat screen TV. Perfect for short or extended stays in Zanzibar.', bedroomCount: 1, bathroomCount: 1 },
  { id: 'room-6', name: 'Standard Room 6', type: 'standard', maxGuests: 2, basePrice: 15000000, amenities: ['WiFi', 'AC', 'Flat screen TV'], images: ['https://images.unsplash.com/photo-1564078516393-cf04bd966897?w=800&q=80'], description: 'Comfortable standard room with modern amenities, air conditioning, and a flat screen TV. Perfect for short or extended stays in Zanzibar.', bedroomCount: 1, bathroomCount: 1 },
  { id: 'room-7', name: 'Standard Room 7', type: 'standard', maxGuests: 2, basePrice: 15000000, amenities: ['WiFi', 'AC', 'Flat screen TV'], images: ['https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=800&q=80'], description: 'Comfortable standard room with modern amenities, air conditioning, and a flat screen TV. Perfect for short or extended stays in Zanzibar.', bedroomCount: 1, bathroomCount: 1 },
  { id: 'room-8', name: 'Standard Room 8', type: 'standard', maxGuests: 2, basePrice: 15000000, amenities: ['WiFi', 'AC', 'Flat screen TV'], images: ['https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800&q=80'], description: 'Comfortable standard room with modern amenities, air conditioning, and a flat screen TV. Perfect for short or extended stays in Zanzibar.', bedroomCount: 1, bathroomCount: 1 },
  { id: 'apartment-1', name: 'Cozy Apartment', type: 'apartment', maxGuests: 4, basePrice: 30000000, amenities: ['WiFi', 'AC', 'Kitchen', 'Balcony', 'Flat screen TV'], images: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80'], description: 'A cozy one-bedroom apartment with a fully equipped kitchen and a private balcony overlooking Zanzibar. Ideal for families and extended stays.', bedroomCount: 1, bathroomCount: 1 },
];

const now = Date.now();
const day = 86400000;

export const MOCK_BOOKINGS: TwigaBooking[] = [
  {
    id: 'BK-001',
    propertyId: 'twiga-residence',
    guestName: 'John Makundi',
    guestEmail: 'john.makundi@email.com',
    guestPhone: '+255712345678',
    roomId: 'room-1',
    checkIn: now + day * 2,
    checkOut: now + day * 5,
    pickupTime: '14:00',
    numberOfGuests: 2,
    totalNights: 3,
    roomPrice: 15000000,
    totalPrice: 45000000,
    paymentId: 'PAY-001',
    source: 'direct',
    status: 'confirmed',
    createdAt: now - day * 3,
    updatedAt: now - day * 3,
  },
  {
    id: 'BK-002',
    propertyId: 'twiga-residence',
    guestName: 'Sarah Kimaro',
    guestEmail: 'sarah.k@email.com',
    guestPhone: '+255765432109',
    roomId: 'room-3',
    checkIn: now + day * 1,
    checkOut: now + day * 4,
    pickupTime: '10:30',
    numberOfGuests: 1,
    totalNights: 3,
    roomPrice: 15000000,
    totalPrice: 45000000,
    paymentId: 'PAY-002',
    source: 'direct',
    status: 'confirmed',
    createdAt: now - day * 5,
    updatedAt: now - day * 5,
  },
  {
    id: 'BK-003',
    propertyId: 'twiga-residence',
    guestName: 'Michael Shayo',
    guestEmail: 'michael.shayo@email.com',
    guestPhone: '+255678901234',
    roomId: 'apartment-1',
    checkIn: now + day * 7,
    checkOut: now + day * 10,
    pickupTime: '16:00',
    numberOfGuests: 4,
    totalNights: 3,
    roomPrice: 30000000,
    totalPrice: 90000000,
    paymentId: 'PAY-003',
    source: 'airbnb',
    status: 'pending_payment',
    createdAt: now - day * 1,
    updatedAt: now - day * 1,
  },
  {
    id: 'BK-004',
    propertyId: 'twiga-residence',
    guestName: 'Grace Mwanga',
    guestEmail: 'grace.m@email.com',
    guestPhone: '+255698765432',
    roomId: 'room-5',
    checkIn: now - day * 10,
    checkOut: now - day * 7,
    numberOfGuests: 2,
    totalNights: 3,
    roomPrice: 15000000,
    totalPrice: 45000000,
    paymentId: 'PAY-004',
    source: 'direct',
    status: 'completed',
    createdAt: now - day * 15,
    updatedAt: now - day * 7,
    checkInCompleted: true,
    checkInCompletedAt: now - day * 10,
  },
  {
    id: 'BK-005',
    propertyId: 'twiga-residence',
    guestName: 'David Ngowi',
    guestEmail: 'david.n@email.com',
    guestPhone: '+255745678901',
    roomId: 'room-2',
    checkIn: now + day * 14,
    checkOut: now + day * 17,
    pickupTime: '12:00',
    numberOfGuests: 2,
    totalNights: 3,
    roomPrice: 15000000,
    totalPrice: 45000000,
    paymentId: 'PAY-005',
    source: 'booking_com',
    status: 'confirmed',
    createdAt: now - day * 2,
    updatedAt: now - day * 2,
  },
  {
    id: 'BK-006',
    propertyId: 'twiga-residence',
    guestName: 'Amina Hassan',
    guestEmail: 'amina.h@email.com',
    guestPhone: '+255723456789',
    roomId: 'room-7',
    checkIn: now - day * 20,
    checkOut: now - day * 18,
    numberOfGuests: 1,
    totalNights: 2,
    roomPrice: 15000000,
    totalPrice: 30000000,
    paymentId: 'PAY-006',
    source: 'direct',
    status: 'cancelled',
    cancelReason: 'Guest requested cancellation',
    cancelledAt: now - day * 22,
    createdAt: now - day * 25,
    updatedAt: now - day * 22,
  },
  {
    id: 'BK-007',
    propertyId: 'twiga-residence',
    guestName: 'Peter Mushi',
    guestEmail: 'peter.m@email.com',
    guestPhone: '+255756789012',
    roomId: 'room-4',
    checkIn: now + day * 5,
    checkOut: now + day * 8,
    pickupTime: '15:30',
    numberOfGuests: 2,
    totalNights: 3,
    roomPrice: 15000000,
    totalPrice: 45000000,
    paymentId: 'PAY-007',
    source: 'direct',
    status: 'pay_on_arrival',
    createdAt: now - day * 1,
    updatedAt: now - day * 1,
  },
];

export const MOCK_PAYMENTS: TwigaPayment[] = [
  {
    id: 'PAY-001',
    bookingId: 'BK-001',
    propertyId: 'twiga-residence',
    amount: 22500000,
    currency: 'TZS',
    method: 'mobile_money',
    flutterwaveRef: 'FLW-001',
    idempotencyKey: 'IDM-001',
    status: 'confirmed',
    mobileProvider: 'mtn',
    phoneNumber: '+255712345678',
    stkPushAttempts: 1,
    webhookReceived: true,
    webhookAt: now - day * 3,
    createdAt: now - day * 3,
    confirmedAt: now - day * 3,
    metadata: { stkPromptSent: true },
  },
  {
    id: 'PAY-002',
    bookingId: 'BK-002',
    propertyId: 'twiga-residence',
    amount: 22500000,
    currency: 'TZS',
    method: 'card',
    flutterwaveRef: 'FLW-002',
    idempotencyKey: 'IDM-002',
    status: 'confirmed',
    stkPushAttempts: 0,
    webhookReceived: true,
    webhookAt: now - day * 5,
    createdAt: now - day * 5,
    confirmedAt: now - day * 5,
    metadata: { last4: '4242' },
  },
  {
    id: 'PAY-003',
    bookingId: 'BK-003',
    propertyId: 'twiga-residence',
    amount: 45000000,
    currency: 'TZS',
    method: 'mobile_money',
    flutterwaveRef: 'FLW-003',
    idempotencyKey: 'IDM-003',
    status: 'initiated',
    mobileProvider: 'airtel',
    phoneNumber: '+255678901234',
    stkPushAttempts: 1,
    webhookReceived: false,
    createdAt: now - day * 1,
    metadata: { stkPromptSent: true, pollingAttempts: 2 },
  },
  {
    id: 'PAY-004',
    bookingId: 'BK-004',
    propertyId: 'twiga-residence',
    amount: 22500000,
    currency: 'TZS',
    method: 'mobile_money',
    flutterwaveRef: 'FLW-004',
    idempotencyKey: 'IDM-004',
    status: 'confirmed',
    mobileProvider: 'tigo',
    phoneNumber: '+255698765432',
    stkPushAttempts: 1,
    webhookReceived: true,
    webhookAt: now - day * 15,
    createdAt: now - day * 15,
    confirmedAt: now - day * 15,
    metadata: { stkPromptSent: true },
  },
  {
    id: 'PAY-005',
    bookingId: 'BK-005',
    propertyId: 'twiga-residence',
    amount: 22500000,
    currency: 'TZS',
    method: 'card',
    flutterwaveRef: 'FLW-005',
    idempotencyKey: 'IDM-005',
    status: 'confirmed',
    stkPushAttempts: 0,
    webhookReceived: true,
    webhookAt: now - day * 2,
    createdAt: now - day * 2,
    confirmedAt: now - day * 2,
    metadata: { last4: '1234' },
  },
  {
    id: 'PAY-006',
    bookingId: 'BK-006',
    propertyId: 'twiga-residence',
    amount: 15000000,
    currency: 'TZS',
    method: 'mobile_money',
    flutterwaveRef: 'FLW-006',
    idempotencyKey: 'IDM-006',
    status: 'refunded',
    mobileProvider: 'mtn',
    phoneNumber: '+255723456789',
    stkPushAttempts: 1,
    webhookReceived: true,
    webhookAt: now - day * 25,
    createdAt: now - day * 25,
    confirmedAt: now - day * 25,
    metadata: { stkPromptSent: true },
  },
  {
    id: 'PAY-007',
    bookingId: 'BK-007',
    propertyId: 'twiga-residence',
    amount: 0,
    currency: 'TZS',
    method: 'pay_on_arrival',
    flutterwaveRef: '',
    idempotencyKey: 'IDM-007',
    status: 'initiated',
    stkPushAttempts: 0,
    webhookReceived: false,
    createdAt: now - day * 1,
    metadata: {},
  },
];
